# lead-crm-library/salesforce/exceptions.py

class SalesforceError(Exception):
    pass
